Repository Suchwinder/Blitz, pull requests merged in 2020-11, with the labels that each got.

#42 update create group, create item, create user
  back_end/postman_collection/postman_collection.json
  back_end/routes/create_group.py
  back_end/routes/items/create_item.py
  back_end/routes/users/create_user.py
Labels: api-endpoint, enhancement

#43 Edit User Complete
  back_end/routes/users/edit_user.py
  back_end/server/__init__.py
Labels: api-endpoint, enhancement

#45 Join group
  back_end/routes/group/create_group.py
  back_end/routes/group/get_group.py
  back_end/routes/group/upload_image.py
  back_end/routes/join_group.py
  back_end/routes/users/edit_user.py
  back_end/server/__init__.py
Labels: api-endpoint, enhancement

#44 Item assignment
  back_end/models/__init__.py
  back_end/routes/assign_item.py
  back_end/routes/group/create_group.py
  back_end/server/__init__.py
Labels: api-endpoint, enhancement

#49 Edit tip rate
  back_end/postman_collection/postman_collection.json
  back_end/routes/group/edit_tip_rate.py
  back_end/server/__init__.py
Labels: api-endpoint

#54 Edit item
  back_end/postman_collection/postman_collection.json
  back_end/routes/items/edit_item.py
  back_end/server/__init__.py
Labels: api-endpoint

#55 Delete item & delete user
  back_end/postman_collection/postman_collection.json
  back_end/routes/items/delete_item.py
  back_end/routes/users/delete_user.py
  back_end/server/__init__.py
Labels: api-endpoint

#57 Freesolo
  .gitignore
  back_end/routes/group/create_group.py
  back_end/routes/group/upload_image.py
  front_end/.gitignore
  front_end/package-lock.json
  front_end/package.json
  front_end/public/index.html
  front_end/src/App.js
  front_end/src/components/Grid/Grid.jsx
  front_end/src/components/create_group/CreateGroup.jsx
  front_end/src/components/grid/Grid.jsx
  front_end/src/components/join_group/JoinGroup.css
  front_end/src/components/join_group/JoinGroup.jsx
  front_end/src/components/places_autocomplete/PlacesAutocomplete.jsx
  front_end/src/components/split_bill/SplitBill.css
  front_end/src/components/split_bill/SplitBill.jsx
  front_end/src/components/upload_button/UploadImage.jsx
Labels: user interface/user experience

#60 Bill split group
  .gitignore
  back_end/routes/items/create_item.py
  back_end/routes/items/delete_item.py
  back_end/routes/items/edit_item.py
  back_end/routes/users/create_user.py
  back_end/routes/users/delete_user.py
  front_end/src/components/split_bill_page/SplitBillPage.js
Labels: user interface/user experience

#76 Added image preview to bill split page
  front_end/src/components/split_bill_page/SplitBillPage.js
Labels: user interface/user experience

#77 fixed logic to account for bug when 2 or more users is assigned to sa…
  back_end/routes/assign_item.py
Labels: api-endpoint, bug

#80 Sockets: Successful Implementation of sockets
  Procfile
  README.md
  back_end/__init__.py
  back_end/main.py
  back_end/server/__init__.py
  back_end/tests/test_db.py
  front_end/build/asset-manifest.json
  front_end/build/index.html
  front_end/build/static/js/2.12632e15.chunk.js
  front_end/build/static/js/2.12632e15.chunk.js.map
  front_end/build/static/js/2.32dfe84e.chunk.js
  front_end/build/static/js/2.32dfe84e.chunk.js.LICENSE.txt
  front_end/build/static/js/2.32dfe84e.chunk.js.map
  front_end/build/static/js/main.30e3c8bf.chunk.js
  front_end/build/static/js/main.30e3c8bf.chunk.js.map
  front_end/build/static/js/main.da739a46.chunk.js
  front_end/build/static/js/main.da739a46.chunk.js.map
  front_end/package-lock.json
  front_end/package.json
  front_end/src/components/split_bill_page/SplitBillPage.js
  requirements.txt
Labels: enhancement

#82 Update receipt
  back_end/postman_collection/postman_collection.json
  back_end/routes/group/reupload_image.py
  back_end/routes/group/upload_image.py
  back_end/server/__init__.py
  front_end/build/asset-manifest.json
  front_end/build/index.html
  front_end/build/static/js/2.32dfe84e.chunk.js
  front_end/build/static/js/2.32dfe84e.chunk.js.map
  front_end/build/static/js/2.75cb1de5.chunk.js
  front_end/build/static/js/2.75cb1de5.chunk.js.LICENSE.txt
  front_end/build/static/js/2.75cb1de5.chunk.js.map
  front_end/build/static/js/main.0cc305cb.chunk.js
  front_end/build/static/js/main.0cc305cb.chunk.js.map
  front_end/build/static/js/main.da739a46.chunk.js
  front_end/build/static/js/main.da739a46.chunk.js.map
  front_end/src/components/create_group/CreateGroup.jsx
  front_end/src/components/split_bill_page/SplitBillPage.js
Labels: api-endpoint, user interface/user experience

#84 QRCode
  Procfile
  README.md
  front_end/build/asset-manifest.json
  front_end/build/index.html
  front_end/build/static/js/2.75cb1de5.chunk.js
  front_end/build/static/js/2.75cb1de5.chunk.js.map
  front_end/build/static/js/2.7e2a8338.chunk.js
  front_end/build/static/js/2.7e2a8338.chunk.js.LICENSE.txt
  front_end/build/static/js/2.7e2a8338.chunk.js.map
  front_end/build/static/js/main.0cc305cb.chunk.js
  front_end/build/static/js/main.0cc305cb.chunk.js.map
  front_end/build/static/js/main.a1054183.chunk.js
  front_end/build/static/js/main.a1054183.chunk.js.map
  front_end/package-lock.json
  front_end/package.json
  front_end/src/components/split_bill_page/SplitBillPage.js
Labels: enhancement

#85 Bugfixes
  back_end/routes/users/delete_user.py
Labels: bug
